scaleio-mdm:
  links: 
   - scaleio-sds:sds
  label:
    io.rancher.scaleio: mdm
  environment:
    USERNAME: ${SCALEIO_USERNAME}
    PASSWORD: ${SCALEIO_PASSWORD}
    SIZE: ${SCALEIO_VOLUME_SIZE}
  privileged: true
  image: wlan0/rexray
  command: ["sleep", "100000"]

scaleio-sds:
  links: 
   - scaleio-mdm:mdm
  label:
    io.rancher.scaleio: sds
  environment:
    USERNAME: ${SCALEIO_USERNAME}
    PASSWORD: ${SCALEIO_PASSWORD}
    SIZE: ${SCALEIO_VOLUME_SIZE}
  image: wlan0/rexray
  privileged: true
  volumes:
    - /var/run:/host/var/run
  command: ["sleep", "100000"]

scaleio-sdc:
  links:
   - scaleio-mdm: mdm
  environment:
    USERNAME: ${SCALEIO_USERNAME}
    PASSWORD: ${SCALEIO_PASSWORD}
    SIZE: ${SCALEIO_VOLUME_SIZE}
  labels:
    io.rancher.scheduler.global: ‘true’
    io.rancher.scaleio: sdc
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.scaleio=mdm
  image: wlan0/rexray
  command: ["sleep", "100000"]
